In [1]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [2]:
# Importing the required library

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics


In [3]:
# The dataset url
# path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [4]:
# Importing the data

df = pd.read_csv(r"C:\Users\USER\Downloads\Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [5]:
# Data Processing

# 1. One hot encoding to convert categorical variables to binary variables.

df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

In [6]:
# 2. Replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column

df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

In [11]:
# Training Data and Test Data

df_sydney_processed.drop('Date',axis=1,inplace=True)

In [12]:
df_sydney_processed = df_sydney_processed.astype(float)

In [13]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

In [14]:
y = df['RainTomorrow'].values
y[0:5]

array(['Yes', 'Yes', 'Yes', 'Yes', 'Yes'], dtype=object)

In [16]:
# Use the train_test_split function to split the features and Y dataframes with a test_size of 0.2 and the random_state set to 10

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)

# Now X_train and y_train are your training features and labels
# X_test and y_test are your testing features and labels
print ('Train set:', y_train.shape,  y_train.shape)
print ('Test set:', y_test.shape,  y_test.shape)

Train set: (2616,) (2616,)
Test set: (655,) (655,)


In [17]:
df.columns

Index(['Date', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [18]:
X = df[[ 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow']] .values  #.astype(float)
X[0:5]

array([[19.5, 22.4, 15.6, 6.2, 0.0, 'W', 41, 'S', 'SSW', 17, 20, 92, 84,
        1017.6, 1017.4, 8, 8, 20.7, 20.9, 'Yes', 'Yes'],
       [19.5, 25.6, 6.0, 3.4, 2.7, 'W', 41, 'W', 'E', 9, 13, 83, 73,
        1017.9, 1016.4, 7, 7, 22.4, 24.8, 'Yes', 'Yes'],
       [21.6, 24.5, 6.6, 2.4, 0.1, 'W', 41, 'ESE', 'ESE', 17, 2, 88, 86,
        1016.7, 1015.6, 7, 8, 23.5, 23.0, 'Yes', 'Yes'],
       [20.2, 22.8, 18.8, 2.2, 0.0, 'W', 41, 'NNE', 'E', 22, 20, 83, 90,
        1014.2, 1011.8, 8, 8, 21.4, 20.9, 'Yes', 'Yes'],
       [19.7, 25.7, 77.4, 4.8, 0.0, 'W', 41, 'NNE', 'W', 11, 6, 88, 74,
        1008.3, 1004.8, 8, 8, 22.5, 25.5, 'Yes', 'Yes']], dtype=object)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)


print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (2616, 66) (2616,)
Test set: (655, 66) (655,)


In [20]:
# Create and train a Linear Regression model called LinearReg using the training data (x_train, y_train)

LinearReg =  LinearRegression()

# Train the model using the training data
LinearReg.fit(X_train, y_train)

LinearRegression()

In [21]:
#  Now we use the predict method on the testing data (x_test) and save it to the array predictions

predictions = LinearReg.predict(X_test)
predictions

array([ 1.31792068e-01,  2.76153564e-01,  9.78164673e-01,  2.87467957e-01,
        1.32379532e-01,  4.60479736e-01,  3.56779099e-01,  8.56395721e-01,
        6.74995422e-01,  3.82099152e-02,  4.87899780e-03,  2.81162262e-01,
        3.39096069e-01,  7.81078339e-02,  6.26049042e-02,  5.64468384e-01,
       -6.15940094e-02,  5.24145126e-01,  1.53787613e-01,  3.59622955e-01,
        6.05373383e-02,  9.03495789e-01,  4.67285156e-01,  2.03378677e-01,
       -7.10830688e-02,  3.83918762e-01,  5.36098480e-01, -2.28557587e-02,
        6.39991760e-01, -9.56687927e-02,  3.78091812e-01,  1.20281219e-01,
       -1.81083679e-02,  5.53779602e-02,  5.63591003e-01,  1.06300735e+00,
       -6.68907166e-03,  5.14431000e-01, -8.83407593e-02,  6.91757202e-02,
        2.44922638e-02,  8.71715546e-01,  2.44647980e-01,  3.94739151e-01,
        2.67513275e-01,  4.46716309e-01, -4.75921631e-02,  1.89382553e-01,
        7.76576996e-01,  1.57682419e-01,  3.94630432e-03, -5.19886017e-02,
        2.07286835e-01, -

In [22]:
# Using the predictions and the y_test dataframe to calculate the value for each metric using the appropriate function

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

LinearRegression_MAE = mean_absolute_error(y_test, predictions)
print(f'Mean Absolute Error (MAE): {LinearRegression_MAE}')
LinearRegression_MSE = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error (MSE): {LinearRegression_MSE}')
LinearRegression_R2 = r2_score(y_test, predictions)
print(f'R-squared (R2) score: {LinearRegression_R2}')

Mean Absolute Error (MAE): 0.2563204088283859
Mean Squared Error (MSE): 0.11572334269886034
R-squared (R2) score: 0.42711844478239436


In [23]:
# Showing the MAE, MSE, and R2 in a tabular format using data frame for the linear model.

import pandas as pd

# Calculate Mean Squared Error (MSE), Mean Absolute Error (MAE), and R-squared (R2)
LinearRegression_MSE = mean_squared_error(y_test, predictions)
LinearRegression_MAE = mean_absolute_error(y_test, predictions)
LinearRegression_R2 = r2_score(y_test, predictions)

In [24]:
# Create a DataFrame to display the metrics
Report = pd.DataFrame({
    'Metric': ['Mean Squared Error (MSE)', 'Mean Absolute Error (MAE)', 'R-squared (R2)'],
    'Value': [LinearRegression_MSE, LinearRegression_MAE, LinearRegression_R2]
})

# Display the DataFrame
print(Report)

                      Metric     Value
0   Mean Squared Error (MSE)  0.115723
1  Mean Absolute Error (MAE)  0.256320
2             R-squared (R2)  0.427118


In [25]:
# Creating and training a KNN model called KNN using the training data (x_train, y_train) with the n_neighbors parameter set to 4

from sklearn.neighbors import KNeighborsClassifier

# Create a KNN model with n_neighbors set to 4
KNN = KNeighborsClassifier(n_neighbors=4)

# Train the model using the training data
KNN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [26]:
#  Using the predict method on the testing data (x_test) and save it to the array predictions.

predictions_knn = KNN.predict(X_test)
predictions_knn

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0.

In [27]:
# Using the predictions and the y_test dataframe to calculate the value for each metric using the appropriate function.

from sklearn.metrics import accuracy_score, jaccard_score, f1_score

# Calculate Accuracy
KNN_Accuracy_Score = accuracy_score(y_test, predictions_knn)
print(f'Accuracy: {KNN_Accuracy_Score}')


# Calculate Jaccard Index
KNN_jaccard_index = jaccard_score(y_test, predictions_knn, pos_label=1)
print(f'KNN Jaccard Index: {KNN_jaccard_index}')


# Calculate F1 Score
KNN_F1_Score = f1_score(y_test, predictions_knn, average='binary')
print(f'KNN F1 Score: {KNN_F1_Score}')

Accuracy: 0.8183206106870229
KNN Jaccard Index: 0.4251207729468599
KNN F1 Score: 0.5966101694915255


In [28]:
# Create and train a Decision Tree model called Tree using the training data (x_train, y_train).

from sklearn.tree import DecisionTreeClassifier

# Create a Decision Tree model
Tree = DecisionTreeClassifier()

# Train the model using the training data
Tree.fit(X_train, y_train) 

DecisionTreeClassifier()

In [29]:
# Use the trained Decision Tree model to make predictions on the testing data and save it to the array predictions
predictions_tree = Tree.predict(X_test)

predictions_tree

array([0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1.

In [30]:
#  Using the predictions and the y_test dataframe calculate the value for each metric using the appropriate function.

from sklearn.metrics import accuracy_score, jaccard_score, f1_score

# Calculate Accuracy Score
Tree_Accuracy_Score = accuracy_score(y_test, predictions_tree)
print(f'Tree Accuracy Score: {Tree_Accuracy_Score}')

# Calculate Jaccard Index
Tree_JaccardIndex =  jaccard_score(y_test, predictions_tree, pos_label=1)
print(f'Tree Jaccard Index: {Tree_JaccardIndex}')

# Calculate F1 Score
Tree_F1_Score  = f1_score(y_test, predictions_tree, average='binary')
print(f'Tree F1 Score: {Tree_F1_Score}')


Tree Accuracy Score: 0.751145038167939
Tree Jaccard Index: 0.3917910447761194
Tree F1 Score: 0.5630026809651475


In [31]:
#  Using the train_test_split function to split the features and Y dataframes with a test_size of 0.2 and the random_state set to 1

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets

x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=1)

In [32]:
from sklearn.linear_model import LogisticRegression

# Create a Logistic Regression model with solver set to 'liblinear'
LR = LogisticRegression(solver='liblinear')

# Train the model using the training data
LR.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [33]:
# Use the trained Logistic Regression model to make predictions on the testing data

predictions = LR.predict(X_test)

In [34]:
# Use the trained Logistic Regression model to obtain probability estimates on the testing data

predict_proba = LR.predict_proba(X_test)[:, 1]

In [35]:
# sing the predictions, predict_proba and the y_test dataframe calculate the value for each metric using the appropriate function

from sklearn.metrics import accuracy_score, jaccard_score, f1_score, log_loss

# Calculate Accuracy Score
LR_Accuracy_Score = accuracy_score(y_test, predictions)
print(f'LR Accuracy Score: {LR_Accuracy_Score}')

# Calculate Jaccard Index
LR_JaccardIndex = jaccard_score(y_test, predictions, pos_label=1)
print(f'LR Jaccard Index: {LR_JaccardIndex}')

# Calculate F1 Score
LR_F1_Score = f1_score(y_test, predictions, average='binary')
print(f'LR F1 Score: {LR_F1_Score}')

# Calculate Log Loss
LR_Log_Loss =  log_loss(y_test, predict_proba)
print(f'LR Log Loss: {LR_Log_Loss}')

LR Accuracy Score: 0.7221374045801526
LR Jaccard Index: 0.0
LR F1 Score: 0.0
LR Log Loss: 0.6097874399122829


In [36]:
from sklearn.svm import SVC

# Create an SVM model
SVM = SVC()

# Train the model using the training data
SVM.fit(X_train, y_train)

SVC()

In [37]:
# Use the trained SVM model to make predictions on the testing data

predictions = SVM.predict(X_test)
predictions

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [38]:
# Using the predictions and the y_test dataframe to calculate the value for each metric using the appropriate function.

from sklearn.metrics import accuracy_score, jaccard_score, f1_score

# Calculate Accuracy Score
SVM_Accuracy_Score =  accuracy_score(y_test, predictions)
print(f'SVM Accuracy Score: {SVM_Accuracy_Score }')

# Calculate Jaccard Index
SVM_JaccardIndex = jaccard_score(y_test, predictions, pos_label=1)
print(f'SVM Jaccard Index: {SVM_JaccardIndex}')

# Calculate F1 Score
SVM_F1_Score = f1_score(y_test, predictions, average='binary')
print(f'SVM F1 Score: {SVM_F1_Score}')

SVM Accuracy Score: 0.7221374045801526
SVM Jaccard Index: 0.0
SVM F1 Score: 0.0


In [39]:
# To show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.
# LogLoss is only for Logistic Regression Model

# Create a DataFrame for metrics
Report = {
    'Model': ['Linear Regression', 'KNN', 'Decision Tree', 'Logistic Regression', 'SVM'],
    'Accuracy': [Tree_Accuracy_Score, accuracy_score(y_test, predictions_knn),
                 accuracy_score(y_test, predictions_tree), LR_Accuracy_Score, SVM_Accuracy_Score],
    'Jaccard Index': [0, jaccard_score(y_test, predictions_knn, pos_label=1),
                      jaccard_score(y_test, predictions_tree, pos_label=1), LR_JaccardIndex, SVM_JaccardIndex],
    'F1 Score': [0, f1_score(y_test, predictions_knn, average='binary'),
                 f1_score(y_test, predictions_tree, average='binary'), LR_F1_Score, SVM_F1_Score],
    'Log Loss': [0, 0, 0, LR_Log_Loss, 0]
}

metrics_df = pd.DataFrame(Report)
print(metrics_df)

                 Model  Accuracy  Jaccard Index  F1 Score  Log Loss
0    Linear Regression  0.751145       0.000000  0.000000  0.000000
1                  KNN  0.641221       0.109848  0.197952  0.000000
2        Decision Tree  0.580153       0.148607  0.258760  0.000000
3  Logistic Regression  0.722137       0.000000  0.000000  0.609787
4                  SVM  0.722137       0.000000  0.000000  0.000000
